# Schema for the configuration files of the Formation 2 module.
formation_2.settings:
  type: config_object
  label: 'Formation 2 settings'
  mapping:
    example:
      type: string
      label: 'Example'
    advanced:
      type: string
      label: 'Advanced'
