<?php

/**
 * @file
 * Functions to support theming in the Formation theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function formation_theme_preprocess_html(&$variables) {
  $variables['today'] = time();
}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function formation_theme_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function formation_theme_preprocess_node(&$variables) {

}
